<a href="https://colab.research.google.com/github/kumawatmanish05/Pytorch-/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)


2.9.0+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available.Using CPU.")


GPU is available
Using GPU : Tesla T4


# **Creating a tensor**

In [4]:
#using empty
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [7]:
#Using Zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#Using rand
torch.rand(2,3)

tensor([[0.9854, 0.5101, 0.1011],
        [0.8910, 0.2035, 0.8197]])

In [10]:
#Using seed
# Rand function will generate random numbers every time so for overcome
# from this and for reuse we uses seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
#Using tensor - Customizable tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
#Other Ways

#arange
print("Using arange ->", torch.arange(0,12,2))

#Using Linspace
print("Using linspace ->", torch.linspace(0,10,10))

#Using eye
print("Using eye ->", torch.eye(3))

#Using full
print("Using full ->", torch.full((2,3), 5))

Using arange -> tensor([ 0,  2,  4,  6,  8, 10])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


# **Tensor Shapes**

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [22]:
#If we wnat to create a tensor will the same shape like x
torch.empty_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

# **Tensors Data Types**

In [26]:
#find data type
x.dtype

torch.int64

In [27]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3],dtype = torch.float32)

tensor([1., 2., 3.])

In [29]:
#using X to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |
