<a href="https://colab.research.google.com/github/kumawatmanish05/Pytorch-/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)


2.9.0+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available.Using CPU.")


GPU is available
Using GPU : Tesla T4


# **Creating a tensor**

In [4]:
#using empty
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [7]:
#Using Zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#Using rand
torch.rand(2,3)

tensor([[0.9854, 0.5101, 0.1011],
        [0.8910, 0.2035, 0.8197]])

In [10]:
#Using seed
# Rand function will generate random numbers every time so for overcome
# from this and for reuse we uses seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
#Using tensor - Customizable tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
#Other Ways

#arange
print("Using arange ->", torch.arange(0,12,2))

#Using Linspace
print("Using linspace ->", torch.linspace(0,10,10))

#Using eye
print("Using eye ->", torch.eye(3))

#Using full
print("Using full ->", torch.full((2,3), 5))

Using arange -> tensor([ 0,  2,  4,  6,  8, 10])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


# **Tensor Shapes**

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [22]:
#If we wnat to create a tensor will the same shape like x
torch.empty_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [30]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# **Tensors Data Types**

In [26]:
#find data type
x.dtype

torch.int64

In [27]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [28]:
torch.tensor([1,2,3],dtype = torch.float32)

tensor([1., 2., 3.])

In [31]:
#using X to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# **Mathematical Operations**

** 1.Scaler Operation**

In [32]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [39]:
# addition
x+2

# substraction
x-2

# multiplication
x*3

# division
x/3

# int division
(x*100)//3

#mod
((x*100)//3)%2

# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

**2.Element wise operation**

In [41]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)


tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])
tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])


In [49]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2015, 0.2475],
        [0.2168, 0.2420]])

In [50]:
c = torch.tensor([-1,-2,-3,-4])

In [51]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [52]:
#negative
torch.neg(c)

tensor([1, 2, 3, 4])

In [53]:
#round
torch.round(torch.tensor([1.2,1.5,1.8]))

tensor([1., 2., 2.])

In [54]:
#ceil
torch.ceil(torch.tensor([1.2,1.5,1.8]))

tensor([2., 2., 2.])

In [55]:
# floor
torch.floor(torch.tensor([1.2,1.5,1.8]))

tensor([1., 1., 1.])

In [56]:
# clamp
torch.clamp(torch.tensor([1.2,1.5,1.8]), min=2, max=3)

tensor([2., 2., 2.])

**3. Reduction operation**


In [68]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 0., 5.],
        [7., 5., 9.]])

In [61]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([14., 19.])

In [63]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([3.5000, 6.0000, 7.0000])

In [64]:
# median
torch.median(e)

tensor(5.)

In [66]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9.)
tensor(0.)


In [69]:
# product
torch.prod(e)

tensor(0.)

In [70]:
# standard deviation
torch.std(e)

tensor(3.0332)

In [71]:
# variance
torch.var(e)

tensor(9.2000)

In [74]:
# argmax gives postion of largest number in a tensor
print(torch.argmax(e))

# argmin gives postion of smallest number in a tensor
print(torch.argmin(e))

tensor(5)
tensor(1)


**4. Matrix Operations**

In [75]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[9, 7, 5],
        [9, 8, 9]])
tensor([[7, 9],
        [2, 6],
        [7, 7]])


In [77]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[112, 158],
        [142, 192]])

In [78]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [79]:
# transpose
torch.transpose(f, 0, 1)

tensor([[9, 9],
        [7, 8],
        [5, 9]])

In [80]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 3., 6.],
        [1., 5., 5.],
        [0., 4., 3.]])

In [81]:
# determinant
torch.det(h)

tensor(-25.0000)

In [82]:
# inverse
torch.inverse(h)

tensor([[ 0.2000, -0.6000,  0.6000],
        [ 0.1200, -0.9600,  1.3600],
        [-0.1600,  1.2800, -1.4800]])

**5. Comparison operations**

In [83]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 8, 3],
        [3, 5, 0]])
tensor([[6, 4, 0],
        [8, 4, 7]])


In [87]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

**6. Special functions**


In [88]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 3., 8.],
        [5., 6., 2.]])

In [89]:
# log
torch.log(k)

tensor([[0.6931, 1.0986, 2.0794],
        [1.6094, 1.7918, 0.6931]])

In [90]:
# exp
torch.exp(k)

tensor([[   7.3891,   20.0855, 2980.9580],
        [ 148.4132,  403.4288,    7.3891]])

In [91]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 1.7321, 2.8284],
        [2.2361, 2.4495, 1.4142]])

In [92]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9526, 0.9997],
        [0.9933, 0.9975, 0.8808]])

In [93]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0474, 0.0474, 0.9975],
        [0.9526, 0.9526, 0.0025]])

In [94]:
# relu
torch.relu(k)

tensor([[2., 3., 8.],
        [5., 6., 2.]])

**7 . Inplace Operations**

In [95]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0103, 0.9516, 0.2855],
        [0.2324, 0.9141, 0.7668]])
tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])


In [96]:
m.add_(n)

tensor([[0.1762, 1.3909, 0.5098],
        [1.1259, 0.9638, 0.9448]])

In [97]:
m

tensor([[0.1762, 1.3909, 0.5098],
        [1.1259, 0.9638, 0.9448]])

In [98]:
n

tensor([[0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780]])

In [99]:
torch.relu(m)

tensor([[0.1762, 1.3909, 0.5098],
        [1.1259, 0.9638, 0.9448]])

In [100]:
m.relu_()

tensor([[0.1762, 1.3909, 0.5098],
        [1.1259, 0.9638, 0.9448]])

In [101]:
m

tensor([[0.1762, 1.3909, 0.5098],
        [1.1259, 0.9638, 0.9448]])

**8 . Copying a Tensor**

In [102]:
a = torch.rand(2,3)
a

tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [103]:
b = a

In [104]:
b

tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [105]:
a[0][0] = 0

In [106]:
a

tensor([[0.0000, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [107]:
b

tensor([[0.0000, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [108]:
id(a)

140252451173024

In [109]:
id(b)

140252451173024

In [110]:
b = a.clone()

In [111]:
a

tensor([[0.0000, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [112]:
b

tensor([[0.0000, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [113]:
a[0][0] = 10

In [114]:
a

tensor([[10.0000,  0.1893,  0.9186],
        [ 0.2131,  0.3957,  0.6017]])

In [115]:
b

tensor([[0.0000, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])

In [116]:
id(a)

140252451173024

In [117]:
id(b)

140252451160144